import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ScrollArea, ScrollBar } from "@/components/ui/scroll-area";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Next Auth App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<ScrollArea className="h-[calc(100vh)] w-full overflow-y-auto">
  <main className="flex flex-1 flex-col gap-4 p-4 pt-0">
    {children}
  </main>
  {/* You can include this if using ShadCN's ScrollBar, otherwise it's optional */}
  <ScrollBar orientation="vertical" className="invisible" />
</ScrollArea>

      </body>
    </html>
  );
}
